// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations run against the direct (non-pooled) connection; the app's
  // PrismaClient uses DATABASE_URL (transaction pooler) via lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
