// AI interface contracts for Lifolio's "Decision Structuring Engine" (PRD Part 3).
//
// AI here is not a chat assistant — it only performs the 6 roles the PRD
// grants it (Part 3 §2): structuring, missing-info detection, normalization,
// similarity explanation, reflection analysis, and Decision DNA analysis.
// No provider is wired in yet; `lib/ai/index.ts` currently always returns
// the rule-based stub in `lib/ai/stub-provider.ts`.

/** One of the app's real, already-established case categories (see libraryFilters). */
export type DecisionCategory = "진로/취업" | "학업/전공" | "창업/도전";

// ── Role 1: Decision Structuring ────────────────────────────────────────
// Free text in, skeleton out. Never invents details the user didn't write.
// title and summary both ride along in this same call rather than separate
// ones — a real provider can write all three from one completion; the
// rule-based stub approximates them from whatever it could parse out of
// rawInput (criteria/concerns don't exist yet at this point either way).
//
// title: card lists (history/home) show this, so it should read as a
// short, natural Korean phrase (15-30 chars) that makes the decision
// recognizable at a glance — not a truncated copy of the raw sentence.
//
// summary: shown atop SummaryCard once the structuring loop closes. A
// 2-3 sentence confirmation the user should read and think "yes, that's
// my situation" — never new interpretation or advice, and only there to
// set up the similar-cases list that follows it. Persisted on Decision
// (see prisma/schema.prisma) so resuming an in-progress consult can
// redisplay it without a second AI call.

export interface DecisionStructureInput {
  rawInput: string;
}

export interface DecisionStructureOutput {
  title: string;
  summary: string;
  category?: DecisionCategory;
  background: string;
  situation: string;
  options: string[];
  criteria: string[];
  concerns: string[];
}

// ── Role 2: Missing Information Detection ───────────────────────────────
// Looks only at which required fields are still empty, in a fixed order
// (background → situation → options → criteria → concerns), and returns
// the single next question to ask conversationally. The caller re-invokes
// this after every answer instead of working through a pre-built list, so
// an answer that happens to cover more than one field is never re-asked.

export type StructuredField = "background" | "situation" | "options" | "criteria" | "concerns";

export interface MissingInfoQuestion {
  field: StructuredField;
  question: string;
  inputType: "text" | "choice" | "list";
  choices?: string[]; // present when inputType === "choice"
}

export interface MissingInfoInput {
  background: string;
  situation: string;
  options: string[];
  criteria: string[];
  concerns: string[];
}

/** Null once every required field is filled — that's the loop's exit signal. */
export type MissingInfoOutput = MissingInfoQuestion | null;

// ── Role 3: Normalization ────────────────────────────────────────────────
// Maps a user's own wording ("돈", "스펙") onto the standard vocabulary
// used across criteria/concerns, so similarity search stays accurate.

export interface NormalizeTermInput {
  term: string;
  context: "criteria" | "concern";
}

export interface NormalizeTermOutput {
  normalized: string;
}

// ── Role 4: Similarity Explanation ───────────────────────────────────────
// Cases are found by DB search (see lib/cases-repo.ts), never generated by
// AI. This role only writes the 1-2 sentence "why this case" caption.

export interface SimilarityExplanationInput {
  userCategory: string;
  userCriteria: string[];
  userConcerns: string[];
  caseCriteria: string[];
  caseConcerns: string[];
}

export interface SimilarityExplanationOutput {
  reason: string;
}

// ── Role 5: Reflection Analysis ──────────────────────────────────────────
// Compares what an option's DecisionOption row expected against what the
// Reflection actually reported. Expected data is never re-asked for.

export interface ReflectionAnalysisInput {
  expectedPositive?: string | null;
  expectedNegative?: string | null;
  actualResult: string;
  actualVsExpected: string;
}

export interface ReflectionAnalysisOutput {
  summary: string;
}

// ── Role 6: Decision DNA Analysis (Level 1 only for MVP) ─────────────────
// Only runs over Decisions that already have a completed Reflection.

export interface DecisionDnaInput {
  completedDecisions: Array<{
    category: string;
    criteria: string[];
    concerns: string[];
    satisfaction: number;
    wouldChooseAgain: "YES" | "NO" | "UNSURE";
    decisionHours: number; // time from Decision.createdAt to finalization
  }>;
}

export interface DecisionDnaLevel1Output {
  topValue: string;
  mostCommonConcern: string;
  averageSatisfaction: number;
  wouldChooseAgainRate: number; // 0~1
  aiInsight: string;
  // 실제로 만족도 높았던/다시 선택하겠다고 답한 결정에서 반복된 가치. topValue(스스로
  // 밝힌 기준)와 다를 수도, 같을 수도 있다 — 같으면 억지로 괴리를 지어내지 않는다.
  revealedValue: string;
  // "나도 몰랐던 나": topValue와 revealedValue를 비교한 한 문장.
  valueGapInsight: string;
  // "숨겨진 결정 기준": 실제로 작용한 가치 카테고리 랭킹(최대 3개).
  hiddenValueRanking: string[];
  // "후회를 만드는 요소": 고민 시간(decisionHours)과 후회의 상관관계 한 문장.
  regretDriverInsight: string;
  // "가장 놀라운 발견": 위 분석 중 가장 임팩트 있는 발견 한 줄.
  surprisingInsight: string;
}

// ── Role 7: Decision Trait Analysis ──────────────────────────────────────
// Runs once per Decision, right when it's finalized (status → DECIDED) —
// unlike Role 6, this never waits on a Reflection. Each pair below is a
// single spectrum (rational + emotional always sum to 100, etc.), scored
// 0~100. The caller (lib/trait-repo.ts) blends this into the user's
// cumulative DecisionTraitProfile via EMA — this role only analyzes the one
// decision in front of it, it never sees or manages the running average.

export interface DecisionTraitInput {
  background: string;
  situation: string;
  criteria: string[];
  concerns: string[];
  decisionHours: number; // time from Decision.createdAt to finalization
}

export interface DecisionTraitOutput {
  rational: number;
  emotional: number;
  longTerm: number;
  shortTerm: number;
  planned: number;
  executionFocused: number;
}

export interface AIProvider {
  structureDecision(input: DecisionStructureInput): Promise<DecisionStructureOutput>;
  detectMissingInfo(input: MissingInfoInput): Promise<MissingInfoOutput>;
  normalizeTerm(input: NormalizeTermInput): Promise<NormalizeTermOutput>;
  explainSimilarity(input: SimilarityExplanationInput): Promise<SimilarityExplanationOutput>;
  analyzeReflection(input: ReflectionAnalysisInput): Promise<ReflectionAnalysisOutput>;
  analyzeDecisionDnaLevel1(input: DecisionDnaInput): Promise<DecisionDnaLevel1Output>;
  analyzeDecisionTraits(input: DecisionTraitInput): Promise<DecisionTraitOutput>;
}
